### ISSUE TITLE
Detallar TXT de Bancaribe

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#270]
Por favor detallar la estructura del TXT del banco Bancaribe así como los instructivos adjuntos:
[Estuctura_TXT_Bancaribe.pdf](https://github.com/erpcya/docs/files/4780969/Estuctura_TXT_Bancaribe.pdf)
[DESBANCO_DEL_CARIBE_OBCO20161103150506.txt](https://github.com/erpcya/docs/files/4780970/DESBANCO_DEL_CARIBE_OBCO20161103150506.txt)
[DESBANCO_DEL_CARIBE_MBCO20161103150506.txt](https://github.com/erpcya/docs/files/4780972/DESBANCO_DEL_CARIBE_MBCO20161103150506.txt)
[AFIBANCO_DEL_CARIBE_OBCO20161103115203.txt](https://github.com/erpcya/docs/files/4780973/AFIBANCO_DEL_CARIBE_OBCO20161103115203.txt)
[AFIBANCO_DEL_CARIBE_MBCO20161103115203.txt](https://github.com/erpcya/docs/files/4780974/AFIBANCO_DEL_CARIBE_MBCO20161103115203.txt)
fina

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull requests #403 con los siguientes puntos:
    - Estuctura_TXT_Bancaribe.pdf
    - Ejemplo de Pagos a Terceros Mismo Banco
    - Ejemplo de Pagos a Terceros Otros Bancos

Pendiente por desarrollar en ADempiere los procesos para generar de manera automática los siguientes txt:
    - DESBANCO_DEL_CARIBE_OBCO20161103150506.txt
    - DESBANCO_DEL_CARIBE_MBCO20161103150506.txt
    - AFIBANCO_DEL_CARIBE_OBCO20161103115203.txt
    - AFIBANCO_DEL_CARIBE_MBCO20161103115203.txt
