### ISSUE TITLE
Detallar TXT de Banesco (Proveedores)

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#271]
Por favor detallar la estructura del TXT del banco Banesco (Pago a Proveedores) así como los instructivos adjuntos:
[MUESTRA_PAGO_PROV_ASOCIADOS.txt](https://github.com/erpcya/docs/files/4781019/MUESTRA_PAGO_PROV_ASOCIADOS.txt)
[Generacion_de_Archivos_de_Pagos.pdf](https://github.com/erpcya/docs/files/4781020/Generacion_de_Archivos_de_Pagos.pdf)
[ARCHIVOS_DE_PAGOS.pdf](https://github.com/erpcya/docs/files/4781022/ARCHIVOS_DE_PAGOS.pdf)
[Codigo_Swift_actualizado.xlsx](https://github.com/erpcya/docs/files/4781025/Codigo_Swift_actualizado.xlsx)

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull requests #403 con los siguientes puntos:
    - Generacion_de_Archivos_de_Pagos.pdf
    - ARCHIVOS_DE_PAGOS.pdf
    - Codigo_Swift_actualizado.xlsx
    - Ejemplo de Pagos a Terceros
