### ISSUE TITLE
Detallar TXT de Banesco (Nómina)

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#272]
Por favor detallar la estructura del TXT del banco Banesco (Pago a Empleados) así como los instructivos adjuntos:
[PRUEBANOMINA.txt](https://github.com/erpcya/docs/files/4781033/PRUEBANOMINA.txt)
[MUESTRA_PAGO_PROV_ASOCIADOS.txt](https://github.com/erpcya/docs/files/4781034/MUESTRA_PAGO_PROV_ASOCIADOS.txt)
[Generacion_de_Archivos_de_Pagos.pdf](https://github.com/erpcya/docs/files/4781035/Generacion_de_Archivos_de_Pagos.pdf)
[ARCHIVOS_DE_PAGOS.pdf](https://github.com/erpcya/docs/files/4781036/ARCHIVOS_DE_PAGOS.pdf)
[Codigo_Swift_actualizado.xlsx](https://github.com/erpcya/docs/files/4781037/Codigo_Swift_actualizado.xlsx)

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull requests #403 con los siguientes puntos:
- Generacion_de_Archivos_de_Pagos.pdf
- ARCHIVOS_DE_PAGOS.pdf
- Codigo_Swift_actualizado.xlsx
- Ejemplo de Pagos de Nómina
