### ISSUE TITLE
Detallar TXT de Banplus

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#273]
Por favor detallar la estructura del TXT del banco Banplus así como los instructivos adjuntos:

[Banplus.zip](https://github.com/erpcya/docs/files/4781055/Banplus.zip)

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull requests #403  con los siguientes puntos:
    - Banplus_On_line.pdf
    - PANTALLAS_SERVICIO_NOMINA_PLUS.ppt
    - PANTALLAS_SERVICIO_NOMINA_PLUS.ppt.pptx
    - PagosMasivos.xlsx
    - Ejemplo de Pagos a Terceros
