### ISSUE TITLE
Detallar TXT de Banco Fondo Comun

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#274]
Por favor detallar la estructura del TXT del banco BFC así como los instructivos adjuntos:
[Instructivo_TXT_Proveedores_BFC.pdf](https://github.com/erpcya/docs/files/4781079/Instructivo_TXT_Proveedores_BFC.pdf)
[BFC_Banco_Fondo__Común__C.A._Banco_Universal_SP-_1000039.txt](https://github.com/erpcya/docs/files/4781080/BFC_Banco_Fondo__Comun__C.A._Banco_Universal_SP-_1000039.txt)

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull requests #403 con los siguientes puntos:
- Instructivo_TXT_Proveedores_BFC.pdf
- Ejemplo de Pagos a Terceros
