### ISSUE TITLE
Detallar TXT de BOD

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#275]
Por favor detallar la estructura del TXT del banco BOD así como los instructivos adjuntos:
[Formato_Pagos_BOD.xlsx](https://github.com/erpcya/docs/files/4781092/Formato_Pagos_BOD.xlsx)

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull requests #405 con los siguientes puntos:
- Formato_Pagos_BOD.xlsx
- Ejemplo de Pagos a Proveedores
