### ISSUE TITLE
Detallar TXT de Exterior

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#276]
Por favor detallar la estructura del TXT del banco Exterior así como los instructivos adjuntos:
[Asistente_Integral_Estructura_Pago_a_Proveedores.pdf](https://github.com/erpcya/docs/files/4781099/Asistente_Integral_Estructura_Pago_a_Proveedores.pdf)
[Pago_Nomina_y_Proveedores.pdf](https://github.com/erpcya/docs/files/4781100/Pago_Nomina_y_Proveedores.pdf)

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull requests #405 con los siguientes puntos:

- Asistente_Integral_Estructura_Pago_a_Proveedores.pdf
- Pago_Nomina_y_Proveedores.pdf
- Ejemplo de Pagos a Proveedores y Nómina
