### ISSUE TITLE
Detallar TXT de Venezuela (Proveedores)

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#284]
Por favor detallar la estructura del TXT del banco Venezuela (Proveedores) así como los instructivos adjuntos:
[Venezuela.zip](https://github.com/erpcya/docs/files/4781193/Venezuela.zip)

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull requests #405 con los siguientes puntos:

FormatoDeArchivoPagoProveedores.pdf
Ejemplo de Pagos a Proveedores
