### ISSUE TITLE
Documentar TXT de Declaración de IVA

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#322]
Por favor documentar el proceso de exportación de TXT de Declaraciones de IVA, este debe contener como activos los documentos adjuntos así como un ejemplo generado desde ADempiere del TXT y la estructura que debe llevar:
[Formato_TXT_IVA.pdf](https://github.com/erpcya/docs/files/4860154/Formato_TXT_IVA.pdf)

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull request #434
