### ISSUE TITLE
Documentar XML de ISLR

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#323]
Por favor documentar el proceso de exportación de XML de Declaraciones de ISLR, este debe contener como activos los documentos adjuntos así como un ejemplo generado desde ADempiere del XML y la estructura que debe llevar:
[Formato_XML_ISLR.pdf](https://github.com/erpcya/docs/files/4860156/Formato_XML_ISLR.pdf)

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull request #434
