### ISSUE TITLE
Documentar funcionalidad de entrega de activos

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#351]
Por favor documentar la funcionalidad de entrega de activos que ya se encuentra como un estándar de ADempiere aquí: https://github.com/adempiere/adempiere/issues/3085
![Deliver_Asset](https://user-images.githubusercontent.com/2333092/77675813-cffaff80-6f63-11ea-8de4-dbc15c576cb4.gif)

**Comment by TaniaLucena** [comment]
Issues resuelto en el pull request #444
