### ISSUE TITLE
Detallar TXT de Banplus (Nómina)

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#354]
Por favor detallar la estructura del TXT del banco Banplus (Nómina) así como los instructivos adjuntos:
[Banplus_PagoNomina_TXT.zip](https://github.com/erpcya/docs/files/5069755/Banplus_PagoNomina_TXT.zip)

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull requests #403 con los siguientes puntos:
    - Banplus_On_line.pdf
    - PANTALLAS_SERVICIO_NOMINA_PLUS.ppt
    - PANTALLAS_SERVICIO_NOMINA_PLUS.ppt.pptx
    - Banplus_PagoNomina_TXT.xls
    - Ejemplo de Pagos de Nómina
