### ISSUE TITLE
Actualizar documentación de Consulta de Precios

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#415]
La consulta de precios ha cambiado mucho desde la última actualización. Estuve revisando y la documentación muestra capturas de pantallas que no corresponden con lo que actualmente se tiene: https://docs.erpya.com/es/4.0.0/adempiere/quote-to-invoice/consultation-of-product-prices.html
![search-result](https://user-images.githubusercontent.com/2333092/99683760-14895d00-2a57-11eb-9cff-5c4bbcfa43e1.png)

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull requests #428

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull requests #431
