### ISSUE TITLE
Especificar los casos de uso en Anular Transaciones de Venta

### ISSUE THREAD

**Issue by yamelsenih** [erpcya/docs-rst#447]
En el documento para [Anular Transaccion de Ventas](https://docs.erpya.com/es/latest/adempiere/pos-management/void-sales-transaction.html#consulta-de-documentos-generados) no se detallan los distintos casos de uso en los cuales aplica o no devolución a almacén.

- Cuando se tiene configurado el Tipo de Documento "Orden Facturada"
- Cuando se tiene configurado el Tipo de Documento "Orden POS"

**Comment by TaniaLucena** [comment]
Issue resuelto en el pull request #450
